#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ if data.values.namespace!="failk8s-operator":

#@overlay/match by=overlay.subset({"kind":"Namespace", "metadata":{"name": "failk8s-operator"}})
#@overlay/remove
---

#@ end

#@overlay/match by=overlay.subset({"kind":"Deployment","metadata": {"name": "failk8s-operator"}})
---
metadata:
  #@overlay/match missing_ok=True
  namespace: #@ data.values.namespace

#@overlay/match by=overlay.subset({"kind":"ServiceAccount","metadata": {"name": "failk8s-operator"}})
---
metadata:
  #@overlay/match missing_ok=True
  namespace: #@ data.values.namespace

#@overlay/match by=overlay.subset({"kind":"ClusterRoleBinding", "metadata": {"name": "failk8s-operators"}})
---
subjects:
#@overlay/match by=overlay.all
- kind: ServiceAccount
  #@overlay/match missing_ok=True
  namespace: #@ data.values.namespace