#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ if data.values.wildcard.create==True:

#@overlay/match by=overlay.subset({"kind":"SecretCopierConfig","metadata": {"name": "wildcard"}})
---
spec:
  rules:
  #@overlay/match by=lambda i,l,r: "sourceSecret" in l
  - sourceSecret:
      name: #@ data.values.wildcard.name
      namespace: #@ data.values.wildcard.namespace

#@ else:

#@overlay/match by=overlay.subset({"kind":"SecretCopierConfig","metadata": {"name": "wildcard"}})
#@overlay/remove
---

#@ end